name: Build
on: [ push ]
env:
  VERSION_NAME: 0.1.0-alpha.${{github.run_number}}
jobs:
  build_windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create short SHA
        uses: benjlevesque/short-sha@v1.2
        id: short-sha
        with:
          length: 6
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 15
      - name: Download WiX Toolset
        run: Invoke-WebRequest https://github.com/wixtoolset/wix3/releases/download/wix3112rtm/wix311-binaries.zip -OutFile wix.zip
      - name: Unzip WiX Toolset
        run: mkdir wix; tar -xf wix.zip -C wix
      - name: Install WiX Toolset
        run: echo wix | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      - name: Maven Build
        run: mvn --batch-mode --update-snapshots verify "-DversionName=${{env.VERSION_NAME}}+${{steps.short-sha.outputs.sha}}" "-DbuildNumber=${{github.run_number}}"
      - name: Rename artifacts
        run: ren target-fat-jar/vatsim-map-${{env.VERSION_NAME}}+${{steps.short-sha.outputs.sha}}-fat.jar VATprism-${{env.VERSION_NAME}}.jar; ren target-installer/VATprism-${{github.run_number}}.0.0.msi VATprism-${{env.VERSION_NAME}}.msi;
      - name: Github Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{secrets.GITHUB_TOKEN}}
          automatic_release_tag: latest
          prerelease: true
          title: v${{env.VERSION_NAME}}
          files: |
            target-fat-jar/*
            target-installer/*
            LICENSE