name: Build
on: [ push ]
jobs:
  build_windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 15
      - name: Download WiX Toolset
        run: Invoke-WebRequest https://github.com/wixtoolset/wix3/releases/download/wix3112rtm/wix311-binaries.zip -OutFile wix.zip
      - name: Unzip WiX Toolset
        run: mkdir wix; tar -xf wix.zip -C wix
      - name: Install WiX Toolset
        run: echo wix | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      - name: Maven Build
        run: mvn --batch-mode --update-snapshots verify
      - name: Github Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: ${{secrets.GITHUB_TOKEN}}
          automatic_release_tag: latest
          prerelease: true
          title: v0.1.0-alpha
          files: |
            target-fat-jar/*
            target-installer/*
            LICENSE